/**
 * Windows daemon autostart via a per-user Scheduled Task (logon trigger).
 *
 * The macOS LaunchAgent analog on Windows is a per-user Scheduled Task with a
 * logon trigger — NOT a real Windows Service. A service runs in session 0 with
 * no desktop and restricted device access, which breaks the daemon's USB-HID
 * (D200H), audio (wake-word), mDNS, and Stream Deck app integration. A logon
 * task runs in the interactive user session, needs no admin elevation, and uses
 * only the built-in schtasks.exe (no npm dependency).
 *
 * The pure XML/args builder is unit-tested (cross-platform); the schtasks
 * /Create|/Run|/Query|/Delete calls are integration-only (real Windows host +
 * side effects) and are exercised manually per docs/daemon.md.
 */
import { writeFileSync, unlinkSync, mkdirSync } from 'fs';
import { homedir, tmpdir, userInfo } from 'os';
import { dirname, join } from 'path';
import { execSync } from './proc.js';
import { fileURLToPath } from 'url';

export const TASK_NAME = 'AgentDeckDaemon';

export function xmlEscape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Resolve node.exe + cli.js directly rather than the `agentdeck` npm shim: the
// global bin on Windows is an `agentdeck.cmd` wrapper whose quoting breaks the
// Task Scheduler <Command>/<Arguments> split. process.execPath is the running
// node; cli.js sits next to this module in the dist dir.
export function getDaemonNodeTarget(): { node: string; cliJs: string } {
  const distDir = dirname(fileURLToPath(import.meta.url));
  return { node: process.execPath, cliJs: join(distDir, 'cli.js') };
}

export function getCurrentTaskUser(): string {
  const domain = process.env.USERDOMAIN;
  const user = process.env.USERNAME || userInfo().username;
  return domain ? `${domain}\\${user}` : user;
}

/**
 * Where the autostart shim lives. Two small generated files next to the rest of
 * the user data, so the whole launch chain is inspectable on disk.
 */
export function getAutostartPaths(): { cmd: string; vbs: string; log: string } {
  const dir = join(homedir(), '.agentdeck');
  return {
    cmd: join(dir, 'daemon-autostart.cmd'),
    vbs: join(dir, 'daemon-autostart.vbs'),
    log: join(dir, 'daemon-autostart.log'),
  };
}

/** System wscript.exe — resolved from SystemRoot rather than PATH. */
export function getWScriptPath(): string {
  return join(process.env.SystemRoot || 'C:\\Windows', 'System32', 'wscript.exe');
}

/**
 * Batch shim that runs the daemon in the foreground with its output captured.
 *
 * Truncates (`>`) rather than appends: the task fires once per logon and the
 * daemon then runs until logoff, so one file is exactly one boot's worth of log
 * — and it cannot grow without bound across reboots the way an append would.
 * `chcp 65001` is on the first line so a non-ASCII profile path (a Japanese or
 * accented username) survives cmd.exe reading this file.
 */
export function buildAutostartCmd(opts?: { node?: string; cliJs?: string; log?: string }): string {
  const { node, cliJs } = { ...getDaemonNodeTarget(), ...opts };
  const log = opts?.log ?? getAutostartPaths().log;
  return [
    '@chcp 65001 >nul',
    '@echo off',
    `"${node}" "${cliJs}" daemon start --foreground > "${log}" 2>&1`,
    'exit /b %ERRORLEVEL%',
    '',
  ].join('\r\n');
}

/**
 * VBScript shim whose only job is to start the batch file with a hidden window.
 *
 * node.exe is a console-subsystem binary, so Task Scheduler launching it
 * directly pops a console window on every logon — the reported problem.
 * `<Hidden>` in the task XML does not help: it hides the task in the Task
 * Scheduler UI, not the process's window. wscript.exe is GUI-subsystem (nothing
 * flashes) and `WshShell.Run` takes a real show-window flag, which is the
 * supported way to start a console program with no console.
 *
 * It waits (`True`) and forwards the exit code so the task still tracks the
 * live daemon and `<RestartOnFailure>` keeps supervising it — running detached
 * would report success the instant the daemon started.
 */
export function buildAutostartVbs(cmdPath?: string): string {
  const target = cmdPath ?? getAutostartPaths().cmd;
  // Inside a VBScript string literal a double quote is written doubled. Windows
  // paths cannot contain `"`, so quoting the path is all that is needed.
  // Kept to plain ASCII: wscript reads .vbs with the system ANSI codepage, and
  // a UTF-8 em dash here comes back as mojibake on a non-Latin-1 machine.
  return [
    "' Generated by `agentdeck daemon install`: starts the AgentDeck daemon",
    "' with no console window. Safe to delete; reinstall to regenerate.",
    'Set sh = CreateObject("WScript.Shell")',
    `rc = sh.Run("""${target}""", 0, True)`,
    'WScript.Quit rc',
    '',
  ].join('\r\n');
}

export function buildScheduledTaskXml(opts?: { node?: string; cliJs?: string; user?: string; vbs?: string }): string {
  const user = opts?.user ?? getCurrentTaskUser();
  const workingDir = join(homedir(), '.agentdeck');
  // Launch through wscript.exe, not node.exe — see buildAutostartVbs.
  const command = xmlEscape(getWScriptPath());
  // //B = batch mode (no script errors or dialogs), //Nologo = no banner.
  const args = xmlEscape(`//B //Nologo "${opts?.vbs ?? getAutostartPaths().vbs}"`);
  const userEsc = xmlEscape(user);
  // schtasks /XML requires UTF-16 with a BOM (see installWindowsTask); declaring
  // UTF-8 triggers "unable to switch the encoding". The bytes are written as
  // UTF-16LE+BOM at install time to match this declaration.
  return `<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>AgentDeck monitoring daemon (auto-start on logon)</Description>
    <URI>\\${TASK_NAME}</URI>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
      <UserId>${userEsc}</UserId>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>${userEsc}</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
    <RestartOnFailure>
      <Interval>PT1M</Interval>
      <Count>3</Count>
    </RestartOnFailure>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>${command}</Command>
      <Arguments>${args}</Arguments>
      <WorkingDirectory>${xmlEscape(workingDir)}</WorkingDirectory>
    </Exec>
  </Actions>
</Task>`;
}

/**
 * Register (or overwrite) the AgentDeckDaemon scheduled task.
 * Throws if schtasks /Create fails (e.g. group policy disabling user task creation).
 */
export function installWindowsTask(): void {
  // Write the launch chain first — the task points at the .vbs, so registering
  // it before the file exists would leave a task that fails on the next logon.
  const paths = getAutostartPaths();
  mkdirSync(dirname(paths.cmd), { recursive: true });
  writeFileSync(paths.cmd, buildAutostartCmd(), 'utf8');
  writeFileSync(paths.vbs, buildAutostartVbs(paths.cmd), 'utf8');

  const xml = buildScheduledTaskXml({ vbs: paths.vbs });
  const tmpFile = join(tmpdir(), `agentdeck-task-${process.pid}-${Date.now()}.xml`);
  // Write UTF-16LE with a BOM (U+FEFF) — schtasks /XML rejects UTF-8 here.
  writeFileSync(tmpFile, '﻿' + xml, 'utf16le');
  try {
    // /F overwrites an existing task (idempotent; mirrors macOS unload-before-load).
    execSync(`schtasks /Create /TN "${TASK_NAME}" /XML "${tmpFile}" /F`, { stdio: 'pipe' });
  } finally {
    try { unlinkSync(tmpFile); } catch { /* temp cleanup best-effort */ }
  }
}

/** True if the AgentDeckDaemon scheduled task is registered. */
export function taskExists(): boolean {
  try {
    execSync(`schtasks /Query /TN "${TASK_NAME}"`, { stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

/** Start the registered task immediately (so no logout is required). */
export function runWindowsTask(): void {
  execSync(`schtasks /Run /TN "${TASK_NAME}"`, { stdio: 'pipe' });
}

/** Stop a running task instance (best-effort; ignores "not running"). */
export function endWindowsTask(): void {
  execSync(`schtasks /End /TN "${TASK_NAME}"`, { stdio: 'pipe' });
}

/** Delete the registered task (/F suppresses the confirm prompt) and its shims. */
export function deleteWindowsTask(): void {
  execSync(`schtasks /Delete /TN "${TASK_NAME}" /F`, { stdio: 'pipe' });
  const paths = getAutostartPaths();
  for (const file of [paths.vbs, paths.cmd]) {
    try { unlinkSync(file); } catch { /* already gone */ }
  }
}
